version: '3.8'

services:
  api:
    build: ./api
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - rabbitmq
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'

  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - api